[versions]
arrow = "1.2.0"
androidGradlePlugin = "8.0.2"
glide = "4.13.2"
kotlin_verison = "1.9.0"
gson = "2.9.0"
kotlinxCoroutinesAndroid = "1.7.2"
kotlinxCoroutinesCore = "1.7.2"
retrofit = "2.9.0"
cardview = "1.0.0"
okhttp="4.11.0"
okio="3.4.0"
coroutine="1.7.3"
androidx-core-ktx="1.10.1"
androidx-viewpager2="1.0.0"
androidx-appcompat-appcompat="1.6.1"
androidx-activity-ktx="1.7.2"
android-material="1.9.0"
constraintLayout="2.1.4"
coordinateLayout="1.2.0"
lifecycle="2.6.1"
hilt_version="2.47"
coil = "2.4.0"
androidxHiltNavigationCompose = "1.0.0"
hilt = "2.47"
hiltExt = "1.0.0"
recyclerview="1.3.1"
junit4 = "4.13.2"
androixJunit="1.1.5"
espresso="3.5.1"
rxandroid = "3.0.0"
rxjava = "3.1.1"
x_crash="3.0.0"

kotlin = "1.9.0"
kotlinxCoroutines = "1.7.3"
kotlinxDatetime = "0.4.0"
kotlinxSerializationJson = "1.5.1"
ktor = "1.6.3"
exfiinterface="1.3.6"
exoplayer = "2.19.1"

room = "2.5.2"

mmkv = "1.2.15"
kotlinxCollectionsImmutable = "0.3.5"
# other versions

[libraries]
adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
android-gradle-build-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-optics = { module = "io.arrow-kt:arrow-optics", version.ref = "arrow" }
arrow-opticsreflect = { module = "io.arrow-kt:arrow-optics-reflect", version.ref = "arrow" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience", version.ref = "arrow" }
arrow-atomic = { module = "io.arrow-kt:arrow-atomic", version.ref = "arrow" }
arrow-fx-stm-jvm = { module = "io.arrow-kt:arrow-fx-stm-jvm", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_verison" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = {  module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"  }
arrow-integration-retrofit = { module = "io.arrow-kt:arrow-core-retrofit", version.ref = "arrow" }
arrow-opticsksp-plugin = { module = "io.arrow-kt:arrow-optics-ksp-plugin", version.ref = "arrow" }



coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }

androidx-core-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-viewpager2-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidx-coordinatelayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinateLayout" }
androidx-recyclerview-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity-ktx" }
androidx-appcompat-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat-appcompat" }
google-android-material-material = { module = "com.google.android.material:material", version.ref = "android-material" }
androidx-cardview-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-exfi-interface = { module = "androidx.exifinterface:exifinterface", version.ref = "exfiinterface" }
##ViewModelScope
androidx-lifecycle-lifecycle-viewmodel-ktx  = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
##LifecycleScope
androidx-lifecycle-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
##LiveData
androidx-lifecycle-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }


google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt_version" }
google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt_version" }
google-dagger-hilt-build-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt_version" }
iqiyi-xcrash = { module = "com.iqiyi.xcrash:xcrash-android-lib", version.ref = "x_crash" }



#Image loading
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-video-kt = { group = "io.coil-kt", name = "coil-video", version.ref = "coil" }
#Dependency injection
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }

#Kotlin Immutable Collections
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlin-stdlib-java8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin_verison" }

#Kotlin Coroutines, serialization, datetime...
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }


#Database
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

#MMKV
mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }

#OkHttp and Retrofit
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }

#ExoPlayer
exoplayer-core = { group = "com.google.android.exoplayer", name = "exoplayer-core", version.ref = "exoplayer" }
exoplayer-ui = { group = "com.google.android.exoplayer", name = "exoplayer-ui", version.ref = "exoplayer" }
exoplayer-hls = { group = "com.google.android.exoplayer", name = "exoplayer-hls", version.ref = "exoplayer" }
exoplayer-dash = { group = "com.google.android.exoplayer", name = "exoplayer-dash", version.ref = "exoplayer" }
exoplayer-smoothstreaming = { group = "com.google.android.exoplayer", name = "exoplayer-smoothstreaming", version.ref = "exoplayer" }
exoplayer-cast = { group = "com.google.android.exoplayer", name = "exoplayer-cast", version.ref = "exoplayer" }
exoplayer-extension-mediasession = { group = "com.google.android.exoplayer", name = "extension-mediasession", version.ref = "exoplayer" }

# testsuite
junit-junit = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androixJunit" }
androidx-test-espresso-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }

# other dependencies


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin_verison" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-gradlePlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


